# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
# COPY . /app
COPY test/Remote/website_test.py /app
COPY .env /app

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org beautifulsoup4 python-decouple pushbullet.py

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["python","website_test.py"]