# Use an official Python runtime as a parent image
FROM python:3.9.7-slim@sha256:408de0cf1a057f5501ee6642ad24a4762738f63bacf09fb4c8d861669260b01e as build_stage

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY test/Remote/website_test.py /app

RUN apt update && \ 
    apt install whois

# Install pipreqs
RUN pip install --no-cache pipreqs

# Generate requirements.txt file based on app.py
RUN pipreqs /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt pushbullet.py

# Cleanup after ourselves
RUN pip uninstall -y pipreqs
# RUN pip cache purge

FROM build_stage as run_stage

# Create a new user with a specific user ID
RUN useradd --uid 1001 app_admin

# Switch to the new user
USER app_admin

COPY . /app

# Run app.py when the container launches
CMD ["python","test/Remote/website_test.py"]
