# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY index.html /app
COPY scripts /app/scripts
COPY styles /app/styles

COPY index.html /app
COPY test/Server/test_server.py /app

# Install any needed packages specified in requirements.txt
# RUN pip install --trusted-host pypi.python.org

# Make port 80 available to the world outside this container
EXPOSE 8000

# Run app.py when the container launches
CMD ["python","test_server.py"]